// Generated by CoffeeScript 1.11.1
(function() {
  var M, config, gulp, path, paths, util, watch, watch_hook;

  config = require('../config');

  paths = config.paths;

  M = require('m-require');

  gulp = M.require('gulp');

  util = M.require('gulp-util');

  watch = M.require('gulp-watch');

  path = M.require('path');


  /*
   * 変更を検知したファイルパス（相対パス）
   */

  watch_hook = function(epath) {
    var relativePath;
    util.log(config.border);
    util.log('PATH_', util.colors.yellow(epath));
    relativePath = path.relative(global.baseDir, path.dirname(epath));
    global.hook_path = path.sep + relativePath + path.sep + path.basename(epath);
    return util.log('global.hook_path -> ', util.colors.yellow(global.hook_path));
  };

  gulp.task('watch', function() {
    return watch(["!" + paths.SRC + '/caches/**/*', "!" + paths.SRC + '/px-files/**/*', "!" + paths.SRC + '**/guieditor.ignore/data.json', paths.SRC + '/**/*'], function(e) {
      watch_hook(e.path);
      return gulp.start(["px2publish"]);
    });
  });

}).call(this);
